Your First NumPy Array

In [1]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


Baseball players' height

In [2]:
# Added: read data and put to list
import pandas as pd
dataset = pd.read_csv('baseball.csv')
print("Length of dataset = ", len(dataset))
dataset.head()

Length of dataset =  1015


Name Team       Position  Height  Weight    Age PosCategory
0    Adam_Donachie  BAL        Catcher      74     180  22.99     Catcher
1        Paul_Bako  BAL        Catcher      74     215  34.69     Catcher
2  Ramon_Hernandez  BAL        Catcher      72     210  30.78     Catcher
3     Kevin_Millar  BAL  First_Baseman      72     210  35.43   Infielder
4      Chris_Gomez  BAL  First_Baseman      73     188  35.71   Infielder

In [3]:
# Check data type
height = dataset.iloc[:, [3]].values
type(height)

numpy.ndarray

In [4]:
# Convert numpy array to list
height = height.tolist()
# height = list(height) # this also works
type(height)

list

In [5]:
# height is available as a regular list

# Import numpy
import numpy as np

# Create a Numpy array from height: np_height
np_height = np.array(height)

# Print out np_height
print(np_height)

# Convert np_height to m: np_height_m
np_height_m = np_height * 0.0254

# Print np_height_m
print(np_height_m)

[[74]
 [74]
 [72]
 ..., 
 [75]
 [75]
 [73]]
[[ 1.8796]
 [ 1.8796]
 [ 1.8288]
 ..., 
 [ 1.905 ]
 [ 1.905 ]
 [ 1.8542]]


Baseball player's BMI

In [6]:
# Added: read data and put to list
import pandas as pd
dataset = pd.read_csv('baseball.csv')
height = list(dataset.iloc[:, [3]].values)
weight = list(dataset.iloc[:, [4]].values)

In [7]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Create array from height with correct units: np_height_m
np_height_m = np.array(height) * 0.0254

# Create array from weight with correct units: np_weight_kg
np_weight_kg = np.array(weight) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m ** 2 

# Print out bmi
print(bmi)

[[ 23.11037639]
 [ 27.60406069]
 [ 28.48080465]
 ..., 
 [ 25.62295933]
 [ 23.74810865]
 [ 25.72686361]]


Lightweight baseball players

In [8]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height) * 0.0254
np_weight_kg = np.array(weight) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[[False]
 [False]
 [False]
 ..., 
 [False]
 [False]
 [False]]
[ 20.54255679  20.54255679  20.69282047  20.69282047  20.34343189
  20.34343189  20.69282047  20.15883472  19.4984471   20.69282047
  20.9205219 ]


Subsetting NumPy Arrays

In [9]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight = np.array(weight)
np_height = np.array(height)

# Print out the weight at index 50
print(np_weight[50])

# Print out sub-array of np_height: index 100 up to and including index 110
print(np_height[100:111])

[200]
[[73]
 [74]
 [72]
 [73]
 [69]
 [72]
 [73]
 [75]
 [75]
 [73]
 [72]]


Your First 2D NumPy Array

In [10]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


Baseball data in 2D form

In [11]:
# Added: read data and put to list
import pandas as pd
dataset = pd.read_csv('baseball.csv')
baseball = list(dataset.iloc[:, [3, 4]].values)
print("Type of baseball = ", type(baseball))

Type of baseball =  <class 'list'>


In [12]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create a 2D Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(1015, 2)


Subsetting 2D NumPy Arrays

In [13]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[49,:])

# Select the entire second column of np_baseball: np_weight
np_weight = np_baseball[:,1]
print(np_weight)

# Print out height of 124th player
print(np_baseball[123,0])

[ 70 195]
[180 215 210 ..., 205 190 195]
75


2D Arithmetic

In [15]:
# Added: read data and put to list
import pandas as pd
dataset = pd.read_csv('baseball.csv')
baseball = list(dataset.iloc[:, [3, 5]].values)

In [ ]:
# baseball is available as a regular list of lists
# updated is available as 2D numpy array

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)